substitutions:
  name: "irremote-XXX"
  room: "Office"
  friendly_name: "IRRemote ${room}"
  device_ip: x.x.x.x
  project_name: "D1MiniIRRemote.Remote"
  project_version: v1.0rc1

packages:
  remote_package:
    url: https://github.com/s-gordon/D1MiniIRShield
    ref: ${project_version}
    refresh: 1d
    files:
      - esphome/packages/base.yaml

# Enable Home Assistant API
api:
  encryption:
    key: !secret apikey

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # fast_connect: on
  # manual_ip:
  #   static_ip: ${device_ip}
  #   gateway: !secret gateway
  #   subnet: !secret subnet